WebApplication1/Views/Shared/Components/SearchResult/SearchResultViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Entities;

namespace WebApplication1.Views.Shared.Components.SearchResult
{
    public class SearchResultViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(List<Product> model)
        {
            return View(model);
        }
    }
}

WebApplication1/Views/Shared/Components/Subscription/SubscriptionViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Views.Shared.Components.Subscription
{
    public class SubscriptionViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var model = new SubscriptionVM(); 
            return View(model);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
@using WebApplication1.Helper;
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- Title  -->
    <title>Amado - Furniture Ecommerce Template | Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <!-- Favicon  -->
    <link rel="icon" href="~/img/core-img/favicon.ico">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="~/css/core-style.css">
    <link rel="stylesheet" href="~/style.css">

</head>

<body>
    <!-- Search Wrapper Area Start -->
    <div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">
                        <form action="#" method="get">
                            <input class="search-input" type="search" name="search" id="search" placeholder="Type your keyword...">
                            <button type="submit"><img src="~/img/core-img/search.png" alt=""></button>
                        </form>
                        <div class="search-result">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Search Wrapper Area End -->
    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="index.html"><img src="~/img/core-img/logo.png" alt=""></a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo">
                <a href="index.html"><img src="~/img/core-img/logo.png" alt=""></a>
            </div>
            <!-- Amado Nav -->
            <nav class="amado-nav">
                <ul>
                    <li class="@NavigationHelper.IsPageActive(ViewBag.ActivePage, "Home")"><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="@NavigationHelper.IsPageActive(ViewBag.ActivePage, "Shop")"><a asp-controller="Shop" asp-action="Index">Shop</a></li>
                    <li class="@NavigationHelper.IsPageActive(ViewBag.ActivePage, "Basket")"><a asp-controller="Basket" asp-action="Index">Cart</a></li>
                    <li class="@NavigationHelper.IsPageActive(ViewBag.ActivePage, "Checkout")"><a asp-controller="Checkout" asp-action="Index">Checkout</a></li>
                </ul>
            </nav>
            <!-- Button Group -->
            <div class="amado-btn-group mt-30 mb-100">
                <a href="#" class="btn amado-btn mb-15">%Discount%</a>
                <a href="#" class="btn amado-btn active">New this week</a>
            </div>
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                <a asp-controller="Basket" asp-action="Index" class="cart-nav"><img src="~/img/core-img/cart.png" alt=""> Cart</a>
                <a href="#" class="fav-nav"><img src="~/img/core-img/favorites.png" alt=""> Favourite</a>
                <a href="#" class="search-nav"><img src="~/img/core-img/search.png" alt=""> Search</a>
            </div>
            <!-- Social Button -->
            <div class="social-info d-flex justify-content-between">
                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
        </header>
        <!-- Header Area End -->
        @RenderBody()
    </div>

    <!-- ##### Newsletter Area Start ##### -->
    @await Component.InvokeAsync("Subscription")
    <!-- ##### Newsletter Area End ##### -->
    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <a href="index.html"><img src="~/img/core-img/logo2.png" alt=""></a>
                        </div>
                        <!-- Copywrite Text -->
                        <p class="copywrite">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> & Re-distributed by <a href="https://themewagon.com/" target="_blank">Themewagon</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <a class="nav-link" href="index.html">Home</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="shop.html">Shop</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="product-details.html">Product</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="cart.html">Cart</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="checkout.html">Checkout</a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->
    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
    <script src="~/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="~/js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="~/js/bootstrap.min.js"></script>
    <!-- Plugins js -->
    <script src="~/js/plugins.js"></script>
    <!-- Active js -->
    <script src="~/js/active.js"></script>
    <script src="~/js/search.js"></script>

    @RenderSection("Script",false)
</body>

</html>

WebApplication1/Views/Shared/_ShopPartial.cshtml
@model ShopIndexVM


@foreach (Product product in Model.Products)
{
    <div class="col-sm-6">
        <div class="single-product-wrapper">
            <!-- Product Image -->
            <div class="product-img">
                <img src="img/product-img/@product.ProductImages?.FirstOrDefault()?.Image.ImageUrl" alt="">
                <!-- Hover Thumb -->
                <img class="hover-img" src="img/product-img/@product.ProductImages?.LastOrDefault()?.Image.ImageUrl" alt="">
            </div>

            <!-- Product Description -->
            <div class="product-description d-flex align-items-center justify-content-between">
                <!-- Product Meta Data -->
                <div class="product-meta-data">
                    <div class="line"></div>
                    <p class="product-price">$@product.Price</p>
                    <a asp-controller="Shop" asp-action="ProductDetail" asp-route-id="@product.Id">
                        <h6>@product.Name</h6>
                    </a>
                </div>
                <!-- Ratings & Cart -->
                <div class="ratings-cart text-right">
                    <div class="ratings">
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                    </div>
                    <div class="cart">
                        <a asp-controller="Shop" asp-action="AddToBasket" asp-route-id="@product.Id" data-toggle="tooltip" data-placement="left" title="Add to Cart"><img src="img/core-img/cart.png" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}